services:
  - type: web
    name: trader-bot-mg-v2
    env: python
    region: frankfurt
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: "10000"
      - key: TELEGRAM_TOKEN
        value: "8233744779:AAGRZSeHNb0Grid1GZLahx89EpZtwTlxukuE"
    plan: free
